version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
- x86
- x64
build:
  project: source/ffplay.sln
  verbosity: minimal
artifacts:
- path: source\Release\ffplay.exe
  name: win32
- path: dependencies\ffmpeg-4.2.1-win32-shared-lgpl\bin\*.dll
  name: win32
- path: dependencies\x64\*.dll
  name: win32
- path: source\x64\Release\ffplay.exe
  name: win64
- path: dependencies\ffmpeg-4.2.1-win64-shared-lgpl\bin\*.dll
  name: win64
- path: dependencies\x64\*.dll
  name: win64